# Generated by Django 3.0 on 2020-01-22 08:22

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='movie_title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('description', models.TextField(blank=True, default='', verbose_name='Movie Description')),
            ],
        ),
    ]
